
-- Soma da Receita e Despesa agrupados pela fonte de recursos.
SELECT R.FONTE_DE_RECURSOS, SUM(ARRECADADO) AS RECEITA, SUM(LIQUIDADO) AS DESPESA FROM RECEITA AS R
INNER JOIN DESPESA AS D ON R.FONTE_DE_RECURSOS = D.FONTE_DE_RECURSOS 
GROUP BY R.FONTE_DE_RECURSOS

-- Soma da despesa agrupada pelo tipo da despesa da maior para a menor
SELECT TIPO_DESPESA, SUM(LIQUIDADO) AS DESPESA FROM DESPESA
GROUP BY TIPO_DESPESA
ORDER BY DESPESA DESC

-- 10 maiores fontes de receita
SELECT TOP 10 FONTE_DE_RECURSOS, SUM(ARRECADADO) AS RECEITA FROM RECEITA
GROUP BY FONTE_DE_RECURSOS
ORDER BY RECEITA DESC

-- 10 maiores fontes de despesa
SELECT TOP 10 FONTE_DE_RECURSOS, SUM(LIQUIDADO) AS DESPESA FROM DESPESA
GROUP BY FONTE_DE_RECURSOS
ORDER BY DESPESA DESC
